server:
  port: 9915

# API Registry client configuration
eureka:
  instance:
    metadata-map:
      # TODO 2 make the service available through the Edge Service (set public property to true)
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8080}/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

logging:
  level:
    com.backbase: INFO
    org.springframework: INFO

# Spring health monitoring
management:
  health:
    jms:
      enabled: false
rest:
  locations:
    url: https://api.hsbc.com/open-banking/v2.1/atms


backbase:
  communication:
    outbound: HTTP

brd:
  cbs:
   api:
    credentials:
     username: Test
